version: '3'
services:
  web:
    image: starfinder
    build: .
    env_file: .env
    environment:
      - FLASK_APP=starfinder/starfinder_app.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./starfinder:/code/starfinder
    depends_on:
      - database
    command: /code/web_entrypoint.sh
  database:
    image: percona
    volumes:
      - ./database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
